version: "3"

services:
  pocketbase-app:
    container_name: "pocketbase-app"
    build: .
    ports:
      - "127.0.0.1:8090:8090"
    volumes:
      - ./pb_data:/pocketbase/pb_data/
    tty: true 
